### ISSUE TITLE
TP5 on Azure: Failed to create endpoint on network nat: HNS failed with error

### ISSUE THREAD

**Issue by mathiasconradt** [MicrosoftDocs/Virtualization-Documentation#273]
I had a working **Docker container on Windows Server 2016 TP5 on Azure** running yesterday. I left everything turned on overnight.
The container host was setup properly with the standard _Install-ContainerHost.ps1_ for TP5.

Today I connected to the host machine on Azure again via RDP, the docker container was stopped, and it seems that some Windows updates had been installed automatically.

Now when I try to start the docker container, it fails. I also tried to start a new container, it also fails with the same error:

```
PS C:\Windows\system32> docker start xyz
Error response from daemon: failed to create endpoint xyzon network nat: HNS failed with error : Failed to create endpoint
Error: failed to start containers: xyz
```

I do a `docker inspect` and see that **all the network configurations are gone**:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ef3bc70509a708e7acd3a5a8b79a9a227436edf42080e658d4b7f2089fdc2596",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "ef3bc70509a7",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "29b977495b4d307f968b1c9832e4e0c97e0766358f7f50ca94f80bede4ea681d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
```

Checking the event log of the host machine, I see some error logs from this morning, which might be related since they refer to the network, not sure though:

```
Source: Hyper-V-Netvsc
Error: The VM and host networking components failed to negotiate protocol version '6.0'
```

Screenshot: https://snag.gy/KXf8tQ.jpg

**Docker version:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

```

Searched for the same issue on the Windows Container Forum, but not much help:
https://social.msdn.microsoft.com/Forums/SqlServer/en-US/home?forum=windowscontainers&brandIgnore=True&sort=relevancedesc&searchTerm=HNS

**Comment by JMesser81** [comment]
@mathiasconradt - could you check and see if you have multiple / pre-existing nats on your host:
PS > Get-VMSwitch
PS > Get-NetNat

The docker daemon will try and create a default nat network on your host.

**Comment by JMesser81** [comment]
Also, was the update a new flight / build? Please let me know what build number you are on when executing:
PS > winver

Thanks

**Comment by mathiasconradt** [comment]
@JMesser81 Sorry, I don't have this VM anymore cause I setup a entirely new one meanwhile when the other did not work anymore.
The current (working) one is build `Version 1511, Build 14300.1010`, and I think the previous (broken) one was the same, since I created them with only one day difference on Azure.

**Comment by tutnes** [comment]
I am getting the same issue here:

`C:\Windows\system32\docker.exe: Error response from daemon: failed to create endpoint backstabbing_mestorf on network nat: HNS failed with error : Failed to create endpoint.`

Running Windows 2016 TP5

Containers: 59
 Running: 0
 Paused: 0
 Stopped: 59
Images: 32
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 835.6 MiB
Name: WIN-OHC1HO32M8M
ID: 26TW:WRMF:5TBE:WUNQ:MYF4:VUVA:CD3I:DYDZ:KU2J:HAIU:EMDO:2N2T
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8


Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

**Comment by StefanScherer** [comment]
This seems to be very related to https://github.com/docker/docker/issues/23086

**Comment by tutnes** [comment]
This page also seems to say something about it:
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/work_in_progress

> Beginning in Windows Server Technical Preview 5, NAT creation and port mapping rules are integrated into the ContainerNetwork cmdlets and docker commands. The Windows Host Network Service (HNS) will manage the NAT on your behalf. However, it is possible that an external client could try and create a duplicate port mapping rule using the same NAT created by HNS.

**Comment by silver565** [comment]
Hi,

Apologies if this isn't the right way to go about this. I've got the same issue with the following setup:

Fresh install. winver returns: 1511 (OS Build 14300.1000)
Docker version returns:

 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Pastebin error from the daemon log:

time="2016-05-31T16:45:49.170844500+12:00" level=info msg="Windows default isolation mode: process"
time="2016-05-31T16:45:49.173805300+12:00" level=info msg="[graphdriver] using prior storage driver \"windowsfilter\""
time="2016-05-31T16:45:49.307809900+12:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-05-31T16:45:52.596002000+12:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Failed to create network"
time="2016-05-31T16:45:53.243411500+12:00" level=info msg="Windows default isolation mode: process"
time="2016-05-31T16:45:53.246460400+12:00" level=info msg="[graphdriver] using prior storage driver \"windowsfilter\""
time="2016-05-31T16:45:53.401376600+12:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-05-31T16:45:56.323635000+12:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Failed to create network"

**Comment by JMesser81** [comment]
Are there two NAT instances installed on this host? 
Can you please run C:\> docker network ls and/or
PS > Get-NetNat
PS > Get-VMSwitch

There is a special way to delete duplicate NAT switches if this indeed is the issue. Please don't try and delete manually.

**Comment by CharlieNZ** [comment]
Both commands return nothing

**Comment by JMesser81** [comment]
What is the IP address assigned to your container host? Is it in the range of 172.16.0.0/12?

We will probably need to collect logs. Please follow the procedure here and then email logs to me.

New-NetEventSession NetCap2 -CaptureMode SaveToFile -LocalFilePath C:\NChostAgent1.etl
Add-NetEventProvider "{0c885e0d-6eb6-476c-a048-2457eed3a5c1}" -Level 5 -SessionName NetCap2 
Add-NetEventProvider "{80CE50DE-D264-4581-950D-ABADEEE0D340}" -Level 5 -SessionName NetCap2
Add-NetEventProvider "{D0E4BC17-34C7-43fc-9A72-D89A59D6979A}" -Level 5 -SessionName NetCap2
Start-NetEventSession NetCap2

Repro

Stop-NetEventSession NetCap2

**Comment by CharlieNZ** [comment]
Actually yes, my lab network is in the 172.16.0.0 range. I'll run the commands and send you the output files

**Comment by JMesser81** [comment]
I'm guessing this error is due to the fact that your lab network's prefix is overlapping with the default NAT internal prefix. Please change the NAT default network prefix by doing the following:
1) PS > Stop-Service docker
2) PS > Get-ContainerNetwork | Remove-ContainerNetwork
3) PS > Get-NetNat | Remove-NetNat
4) PS > Get-VMSwitch | Remove-VMSwitch
5) Edit the C:\ProgramData\Docker\runDockerDaemon.cmd and add a '-b "none"' option to the end of dockerd.
6) Start-Service docker
7) C:\> docker network create -d nat --subnet-prefix=<prefix> --default-gateway=<Gateway IP> MyNatNetwork

**Comment by CharlieNZ** [comment]
Sorry for being a pain.. Can you confirm the location of the '-b "none"' ?

![image](https://cloud.githubusercontent.com/assets/8424336/15698514/8b2194a4-2819-11e6-99cc-527e740d6d33.png)

**Comment by JMesser81** [comment]
Hi Charlie,

On second thought, if you know you want NAT to be your default network, you can simply ensure the NAT internal subnet does not collide with your external network by using the --fixed-cidr=<IP Prefix> option added to dockerd. 

Example:
dockerd -H npipe:// --fixed-cidr=192.168.0.0/24
dockerd -H npipe:// -H 0.0.0.0:2976 --fixed-cidr=192.168.0.0/24 --tlsverify ...

If you absolutely do not want to create a NAT as a default container network, then you should add '-b "none"' option to dockerd

Example
dockerd -H npipe:// -b "none"

**Comment by CharlieNZ** [comment]
dockerd -H npipe:// -b "none" has done the trick! Thank you so much! :)

**Comment by mathiasconradt** [comment]
@JMesser81 I am facing the same issue again. To answer your questions further above:

```
PS C:\> Get-VMSwitch
Name SwitchType NetAdapterInterfaceDescription
---- ---------- ------------------------------
nat

PS C:\> Get-NetNat

Name                             : H43c5c620-1874-400a-b96a-a67ff532230c
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 172.16.0.1/12
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True

PS C:\> winver
=> Version 1511, Build 14300.1010
```

How to fix this on Azure?

> I'm guessing this error is due to the fact that your lab network's prefix is overlapping with the default NAT internal prefix.

This does not apply to Azure, does it? I mean, Docker is working fine on Azure for a few days, I even deactivated the Windows Update service this time, and now, when I got back onto the machine, I see that my Docker container has stopped 2 days ago for no reason, I have no idea what has stopped it. But most importantly, I have no idea what's changing the NAT configuration.

I tried to just run `dockerd -H npipe:// -b "none"`, but it failed with:

```
PS C:\> dockerd -H npipe:// -b "none"
time="2016-06-02T13:29:57.488638500Z" level=fatal msg="Error starting daemon: pid file found, ensure docker is not running or delete C:\\ProgramData\\docker.pid"
```

Then I removed the docker.pid file and try it again (I have PS open as Administrator):

```
PS C:\> dockerd -H npipe:// -b "none"
time="2016-06-02T13:33:41.540897400Z" level=fatal msg="open //./pipe/docker_engine: Access is denied."
```

However I new docker.pid file has been created. But when I try to start my Docker container again, I still have the same, original problem (`"HNS failed with error:"`).

Finally I tried the 7 steps you mentioned above, but even though it fails on step 7, it solves the problem:

```
PS C:\> stop-service docker
PS C:\> get-containernetwork | remove-containernetwork
WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As part of that some cmdlet and
parameter names may change in future releases. To learn more about these changes as well as to join in the design process or provide usage feedback please
 refer to http://aka.ms/windowscontainers/powershell

Confirm
Remove-ContainerNetwork will remove the container network "".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
PS C:\> get-netnat | remove-netnat
PS C:\> get-vmswitch | remove-vmswitch
PS C:\> start-service docker
PS C:\> docker network create -d nat --subnet-prefix= --default-gateway= MyNatNetwork
flag provided but not defined: --subnet-prefix
See 'C:\Windows\system32\docker.exe network create --help'.
flag provided but not defined: --subnet-prefix
```

When I now start my docker container again, it works fine.

And the output of `get-vmswitch` and `get-netnat` is now:

```
PS C:\Windows\system32> get-vmswitch
PS C:\Windows\system32> get-netnat
PS C:\Windows\system32>
```

I have the feeling that somehow the host VM gets updates on Azure despite that I have deactivated the Windows Updates service (`wuauserv`). No idea what's going on on Azure.
Maybe I am mistaken here, but I am pretty sure that I had added the German/Germany keyboard under Windows when I setup the VM (so that I have 3 keyboards available: US, German, Swiss), and now it's back to only 2 again (US, Swiss). I also don't know what would've stopped the Docker container - I definitely didn't stop it, didn't even touch the VM at all until today again.

**Comment by mathiasconradt** [comment]
@JMesser81 I also ran the commands you mentioned above

```
New-NetEventSession NetCap2 -CaptureMode SaveToFile -LocalFilePath C:\NChostAgent1.etl
etc.
```

What's the log file you need? Is it this NChostAGent1.etl? I would then email those to you.

**Comment by JMesser81** [comment]
@mathiasconradt - it looks like you forgot to specify the IP subnet prefix (e.g. 192.168.0.0/24) and the default gateway IP (e.g. 192.168.1.1) when you created your custom nat network. 
PS C:\> docker network create -d nat --subnet-prefix=<MISSING> --default-gateway=<MISSING> MyNatNetwork
flag provided but not defined: --subnet-prefix

After you fix that issue, can you send me the output of:
C:\> docker network ls

**Comment by mathiasconradt** [comment]
@JMesser81 Ok, I had just followed the exact steps (copy/paste) as per your comment above https://github.com/Microsoft/Virtualization-Documentation/issues/273#issuecomment-222882509, thought those were intentionally left blank.

Nevertheless, the command still fails. 

```
PS C:\> docker network create -d nat --subnet-prefix=192.168.0.0/24 --default-gateway=192.168.1.1 MyNatNetwork
flag provided but not defined: --subnet-prefix
See 'C:\Windows\system32\docker.exe network create --help'.
flag provided but not defined: --subnet-prefix
```

I also don't see these --subnet-prefix and --default-gateway options when I run `docker.exe network create --help`:

```
PS C:\> docker.exe network create --help
Usage:  docker network create [OPTIONS] NETWORK-NAME
Creates a new network with a name specified by the user
  --aux-address=map[]      auxiliary ipv4 or ipv6 addresses used by Network driver
  -d, --driver=bridge      Driver to manage the Network
  --gateway=[]             ipv4 or ipv6 Gateway for the master subnet
  --help                   Print usage
  --internal               restricts external access to the network
  --ip-range=[]            allocate container ip from a sub-range
  --ipam-driver=default    IP Address Management Driver
  --ipam-opt=map[]         set IPAM driver specific options
  --ipv6                   enable IPv6 networking
  --label=[]               set metadata on a network
  -o, --opt=map[]          set driver specific options
  --subnet=[]              subnet in CIDR format that represents a network segment
```

So I tried the following:

@JMesser81 Ok, I had just followed the exact steps (copy/paste) as per your comment above https://github.com/Microsoft/Virtualization-Documentation/issues/273#issuecomment-222882509, thoughts those were intentionally left blank.

Nevertheless, the command still fails. I also don't see these --subnet-prefix and --default-gateway options when I run `docker.exe network create --help`:

```
PS C:\> docker.exe network create --help
Usage:  docker network create [OPTIONS] NETWORK-NAME
Creates a new network with a name specified by the user
  --aux-address=map[]      auxiliary ipv4 or ipv6 addresses used by Network driver
  -d, --driver=bridge      Driver to manage the Network
  --gateway=[]             ipv4 or ipv6 Gateway for the master subnet
  --help                   Print usage
  --internal               restricts external access to the network
  --ip-range=[]            allocate container ip from a sub-range
  --ipam-driver=default    IP Address Management Driver
  --ipam-opt=map[]         set IPAM driver specific options
  --ipv6                   enable IPv6 networking
  --label=[]               set metadata on a network
  -o, --opt=map[]          set driver specific options
  --subnet=[]              subnet in CIDR format that represents a network segment
```

So I tried the following:

```
PS C:\> docker network create -d nat --subnet=[192.168.0.0/24] --gateway=[192.168.1.1] MyNatNetwork
Invalid subnet <nil> : invalid CIDR address: [192.168.0.0/24]
PS C:\> docker network create -d nat --subnet=[192.168.0.0] --gateway=[192.168.1.1] MyNatNetwork
Invalid subnet <nil> : invalid CIDR address: [192.168.0.0]

```
`docker  version`:

```
PS C:\> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Comment by mathiasconradt** [comment]
@tutnes Thanks for that [link](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/work_in_progress).

> The Windows Host Network Service (HNS) will manage the NAT on your behalf. However, it is possible that an external client could try and create a duplicate port mapping rule using the same NAT created by HNS.

I really wonder though what external client that would be in case of Azure. I just left the machine untouched for few days, then the container just shows today that it has exited 2 days ago. 
Just to be sure no updates would do that, I had explicitly disabled the Windows Update service.

**Comment by JMesser81** [comment]
Sorry for pointing you towards the wrong commands and giving you incomplete information. 

I just verified this act command works on my setup (assuming dockerd was started with -b "none" parameter)

C:\> docker network create -d nat --subnet=192.168.0.0/24 --gateway=192.168.0.1 MyNatNetwork

Make sure the Gateway IP address is in the range of the subnet prefix as shown above. You're previous command of subnet=192.168.0.0/24 --gateway=192.168.1.1 had the gateway IP in the incorrect subnet.

C:\> docker run -it --net=MyNatNetwork windowsservercore cmd.exe

You should be able to ping external addresses now.

**Comment by mathiasconradt** [comment]
@JMesser81 Thank you for the clarification, indeed, **this command now worked. And when I run a new docker container with it, I can now reach it from external.**

However, I just found **another issue**, not related to this one:
Since I want to still use my old container instead of creating a new one from the same original image, due to some changes I had made inside the container meanwhile, but I would need to assign the MyNatNetwork to it, I **tried to create a new image out of this running container**.

```
PS C:\Windows\system32> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
company/mycompany       latest              e081b9d046b7        9 days ago          12.11 GB
windowsservercore   10.0.14300.1000     dbfee88ee9fd        9 weeks ago         9.344 GB
windowsservercore   latest              dbfee88ee9fd        9 weeks ago         9.344 GB

PS C:\Windows\system32> docker ps -a
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS                         PORTS                NAMES
6a4f1ec207bf        company/mycompany       "cmd /S /C 'C:\\company-"   9 days ago          Exited (1067) 25 minutes ago                        mycompany

PS C:\Windows\system32> docker commit mycompany company/mycompany2
Error response from daemon: hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\docker\windowsfilter\b4b3a30008
f1e3b1fbb0f7dda8c3ec027e71564ab3a45a8e1622765d8732c5f5 flavour=1 folder=C:\Windows\TEMP\hcs960930749
```

I will do some additional research on that tomorrow and eventually create a new ticket for this if it turns out to be an unknown issue.

**Comment by nicholasdille** [comment]
I had the exact same issue on my container host running on hardware not on Azure. It happened after an unplanned reboot. Here is what I did to solve this:

1. Get-NetNatStaticMapping | Remove-NetNatStaticMapping
2. Reboot

It seems like some service was still remembering those mappings. Restarting the docker daemon did not solve this but the reboot did.

I hope this helps some of you!

**Comment by StefanScherer** [comment]
With another reboot? Good to know.

**Comment by pizycki** [comment]
Yep, nicholasdille solution worked for me.

**Comment by ToreBerntsen** [comment]
i tried @nicholasdille fix and it worked, but i have to do it every time after a shutdown/reset on the pc, so the started containers before shutdown will not work after restart, before i run 
Get-NetNatStaticMapping | Remove-NetNatStaticMapping
and restarts again, 
any idea how to fix so it doesnt remember the netnatstaticmapping?

**Comment by nicholasdille** [comment]
That is weird. In my case, it was fixed permanently. Are you having unplanned stops of containers with those mappings? E.g. caused by a reboot? When a container is properly stopped, the mappings should be removed. Can you check that?

**Comment by ToreBerntsen** [comment]
okey thanks @nicholasdille  so if i stop all the containers before i reboot or shutdown the pc its fine, but if i dont stop container and reboot i need to run the command Get-NetNatStaticMapping | Remove-NetNatStaticMapping

another thing every time i reboot or start the pc after a shutdown i need to start docker service, is it possible to make it start up automatically?

**Comment by nicholasdille** [comment]
@ToreBerntsen, I don't know if the issue is caused by a reboot with running container. In my opinion, a reboot should handle running containers safely. I can only comment on a hard power down of the whole container host. Do you have insight on reboots with running containers?

**Comment by IrisClasson** [comment]
I can confirm the issue happens after a reboot with running containers. Windows update decided to update our development server last night, and we were unable to restart our containers on the same ports. I tried running the command above, but the error persists. Here are some details from the eventlog, I hope they can be of help. 

I hope somebody manages to sort this out, if I do I'll make sure to return and share the solution

[error.txt](https://github.com/Microsoft/Virtualization-Documentation/files/352513/error.txt)

**Comment by IrisClasson** [comment]
Well, in my case the solution was to uninstall the latest update **(KB3172982)** and reboot. I'll try to install the update again to verify that the issue was (at least partly) due to the update getting stuck - and hopefully I wont have the problem again.

I've had the endpoint problem after reboots and running containers, but clearing the static mappings configured on the NAT instances fixed it.

**Comment by SoCentral2** [comment]
Thanks for this. I had the same problem where it worked on day 1 & didn't work on day 2 - there had been a reboot between days with running containers. I did some of the steps above, most saying they hadn't worked, but eventually my _docker run_ ran :-) . I didn't need to reboot however.

**Comment by yenhao** [comment]
I am also TP5
My case is that if I run ` docker run -itd -p 8000:80 microsoft/iis cmd`
Then, kill this container and remove this cnotainer (or server reboot), next time I could't use 8000 port anymore! 
I need to switch to another port, such as 8001 and so on...

My docker is 
> PS C:\> docker version
> Client:
>  Version:      1.12.0-dev
>  API version:  1.24
>  Go version:   go1.5.3
>  Git commit:   8e92415
>  Built:        Thu May 26 17:08:34 2016
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.12.0-dev
>  API version:  1.24
>  Go version:   go1.5.3
>  Git commit:   8e92415
>  Built:        Thu May 26 17:08:34 2016
>  OS/Arch:      windows/amd64

**Comment by JMesser81** [comment]
@yenhao - After creating a new docker container with a port mapping, could you please check the output of Get-NetNatStaticMapping? Then, after the container is killed, check Get-NetNatStaticMapping again and see if the port mapping is still there.

**Comment by yenhao** [comment]
@JMesser81 
sure!
However, when I was trying yesterday, it appear the new issue. (#25336)
I will try it when I fix this..

**Comment by yenhao** [comment]
@JMesser81 

After create & mapping container
```
StaticMappingID               : 0
NatName                       : Hd47cd4b7-9260-46a8-8c07-d1133e5e3d7c
Protocol                      : TCP
RemoteExternalIPAddressPrefix : 0.0.0.0/0
ExternalIPAddress             : 0.0.0.0
ExternalPort                  : 80
InternalIPAddress             : 172.23.97.27
InternalPort                  : 80
InternalRoutingDomainId       : {00000000-0000-0000-0000-000000000000}
Active                        : True
```

After kill it get nothing!!
I got my windows server 2016 to be 14300.1045.amd64fre.rs1_release_svc.**160705-1059**
It seems like it is okay now!

Thanks

**Comment by Shuliyey** [comment]
@JMesser81 thanks for the workaround

This definitely is a bug, and it occurs randomly, I think I managed to track down what's exactly going.
I've spinned up a docker container with port 80:80 binded
```cmd
docker run -it -d -p 80:80 --restart=always --name=iis microsoft/iis ping -t localhost
```

Now when I restarted my VM/Physical machine, for some reason, this random bug could occur, which the original container is not started. But some where else there's another background process with the same port binding and same process command (as the docker container) being run.

So this is just like there's another hidden container that's an exact clone of the container that was created at the previous step.

This hidden (duplicate) container will have the same port binding as the original one. Hence when we try to create/start a container with the port binding, it won't be able to do the binding as it's already been taken by this hidden container.

I managed to work around this problem using the steps @JMesser81 mentioned previously, but with less steps required
Note this is happening to the below docker version

```cmd
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64
```

```powershell
1) PS > Stop-Service docker
2) PS > Get-ContainerNetwork | Remove-ContainerNetwork
3) PS > Get-NetNat | Remove-NetNat
4) PS > Get-VMSwitch | Remove-VMSwitch
6) Start-Service docker
```

**Comment by JanneRantala** [comment]
Hi,

This seems to be an old thread but I'll try it anyway. I've been starting to get same 

"failed to create endpoint db1 on network nat: HNS failed with error : Unspecified error" error in 

Windows Server 2016 when running docker-compose. This happens very occasionally and I really haven't found any good explanation what causes this or if this has already been fixed. 

I've updated Windows Server with all the latest updates, Docker versions are these:
Client:
 Version:      17.03.0-ce
 API version:  1.24 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25 (minimum version )
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
 Experimental: false
 
And Docker compose:
docker-compose version 1.9.0dev, build 466ebb6
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

Another question is that how Docker in Windows Server 2016 is supposed to be updated when there's newer version available? Does it go through normal Windows Update channel?

Thanks,

Janne

**Comment by StefanScherer** [comment]
@JanneRantala you can update the docker engine with zhe package. https://github.com/OneGet/MicrosoftDockerProvider/blob/developer/README.md

**Comment by JanneRantala** [comment]
Tried updating Docker with command

Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose -Update

but it ends up with this error:

```
> VERBOSE: Using the provider 'DockerMsftProvider' for searching packages.
> VERBOSE: Download size: 0MB
> VERBOSE: Free space on the drive: 73585.54MB
> VERBOSE: Downloading https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json to
> C:\Users\RANTAL~1\AppData\Local\Temp\DockerMsftProvider\DockerDefault_DockerSearchIndex.json
> VERBOSE: About to download
> VERBOSE: Finished downloading
> VERBOSE: Downloaded in 0 hours, 0 minutes, 1 seconds.
> VERBOSE: Performing the operation "Install Package" on target "Package 'Docker' version '17.03.0-ee' from 'DockerDefault'.".
> 
> The package(s) come(s) from a package source that is not marked as trusted.
> Are you sure you want to install software from 'DockerDefault'?
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
> VERBOSE: Updating the docker installation.
> VERBOSE: Unregistering the docker service
> VERBOSE: Removing the docker files
> VERBOSE: Removing the path variable
> VERBOSE: Download size: 13.38MB
> VERBOSE: Free space on the drive: 73623.7MB
> VERBOSE: Downloading https://dockermsft.blob.core.windows.net/dockercontainer/docker-17-03-0-ee.zip to
> C:\Users\RANTAL~1\AppData\Local\Temp\DockerMsftProvider\Docker-17-03-0-ee.zip
> VERBOSE: About to download
> VERBOSE: Finished downloading
> VERBOSE: Downloaded in 0 hours, 0 minutes, 2 seconds.
> VERBOSE: Verifying Hash of the downloaded file.
> VERBOSE: Hash verified!
> VERBOSE: Found C:\Users\RANTAL\AppData\Local\Temp\DockerMsftProvider\Docker-17-03-0-ee.zip to install.
> VERBOSE: Trying to unzip : C:\Users\RANTAL\AppData\Local\Temp\DockerMsftProvider\Docker-17-03-0-ee.zip
> VERBOSE: Preparing to expand...
> VERBOSE: Created 'C:\Program Files\docker\docker.exe'.
> VERBOSE: Created 'C:\Program Files\docker\dockerd.exe'.
> VERBOSE: Trying to enable the docker service...
> VERBOSE: Removing the archive: C:\Users\RANTAL\AppData\Local\Temp\DockerMsftProvider\Docker-17-03-0-ee.zip
> Install-Package : Cannot rename because item at 'C:\Program Files\dummyName' does not exist.
> At line:1 char:1
> + Install-Package -Name docker -ProviderName DockerMsftProvider -Verbos ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
>     + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by PatrickLang** [comment]
What about `Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose`

**Comment by JanneRantala** [comment]
Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose gave me this:

```
VERBOSE: Using the provider 'DockerMsftProvider' for searching packages.
VERBOSE: Download size: 0MB
VERBOSE: Free space on the drive: 73215.89MB
VERBOSE: Downloading https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json to C:\Users\RANTAL~1\AppData\Local\Temp\DockerMsftProvider\DockerDefault_DockerSearchIndex.json
VERBOSE: About to download
VERBOSE: Finished downloading
VERBOSE: Downloaded in 0 hours, 0 minutes, 1 seconds.
VERBOSE: Performing the operation "Install Package" on target "Package 'Docker' version '17.03.0-ee' from 'DockerDefault'.".

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'DockerDefault'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
VERBOSE: Docker 17.03.0-ee-1 already exists. Skipping install. Use -force to install anyway.
```
Docker seemed to start after that update error with start-service docker, so hopefully everything is ok?

**Comment by enderb-ms** [comment]
Closing this issue due to inactivity, and it seems to have been resolved. Please feel free to open this issue again if there is still something we could help with.
